module.exports={
    PRODUCT_COLLECTION:'product',
    USER_COLLECTION:'user',
    ADMIN_COLLECTION:'admin',
    MEN_SHIRT:'m-shirt',
    MEN_TSHIRT:'m-tshirt',
    WOMEN_KURTHIES:'wo-kurthies',
    WOMEN_TSHIRTS:'wo-tshirt',
    CART_COLLECTION:'cart',
    WISHLIST_COLLECTION:'wishlist',
    COUPON_COLLECTION:'coupon',
    ORDER_COLLECTION:'order-collection'
}